name: CI

on:
  push:
    branches: [master, try-import]
  pull_request:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2.1.0
      - name: Check commit
        if: ${{ github.event.pull_request }}
        run: |
          yarn add @commitlint/config-conventional @commitlint/cli
          yarn commitlint --from ${{ github.event.pull_request.base.sha }} --to HEAD

  auto-merge:
    if: ${{ github.ref == 'refs/heads/try-import' }}
    runs-on: ubuntu-latest
    needs: [check-commit]
    steps:
      - name: Checkout MegEngine
        uses: actions/checkout@v2.3.1
        with:
          fetch-depth: '0'
      - name: Merge with master
        run: |
          git config user.name "megvii-mge"
          git config user.email "megengine@megvii.com"
          git fetch origin master
          git checkout -b master origin/master
          git rebase try-import
          git push
  send-dingding:
    runs-on: ubuntu-latest
    needs: [auto-merge]
    if: ${{ always() && github.ref == 'refs/heads/try-import'  }}
    steps:
      - name: run
        uses: zcong1993/actions-ding@master
        with:
          dingToken: ${{ secrets.DINGDING_TOKEN }}
          body: |
            {
              "msgtype": "link",
              "link": {
                  "text": "Workflow ${{ github.run_id }} Failed",
                  "title": "Action Alert",
                  "picUrl": "",
                  "messageUrl": "https://github.com/MegEngine/MegEngine/actions/runs/${{ github.run_id }}"
              }
            }
